[package]
name = "bookmark-cli-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.bookmark-cli]
path = ".."

[[bin]]
name = "import_stdin"
path = "fuzz_targets/import_stdin.rs"
test = false
doc = false
bench = false
